---
title: "Welcome to Shinymodels"
output: html_document
---

###  Welcome to Shinymodels

shiny + tidymodels = shinymodels

The shinymodels app is designed to explore a tidymodels object. Our aim is to visualize the modeled data and help detect any problematic observations while modeling. 

### General purpose

Through various diagnostic plots, we hope to help identify structure that could otherwise go missing. Also, linking multiple graphics can lead to insight not revealed by a single view. Given a model with parameters to tune, the app allows users to compare modeling results for different selections of parameters. In addition, several dataset and observations information can be found and explored in this app.

### Tabs

There are mainly two categories of tabs in the app: 

* **Tuning Parameters tab:** For models with tuning parameters (e.g., [`tune_bayes()`](https://tune.tidymodels.org/reference/tune_bayes.html)), the tab with tuning parameters consists of the data table for the tuning parameters and performance metrics for each candidate model. When the app is first launched, the _default configuration_ is based on the optimal value of the first metric. Selecting a row in the tuning parameter table selects the related model which should then update the diagnostic plots in the Plots tab(s).  

* **Plots tab (s):** The Plots tab consists of diagnostic plots to explore the model object. Clicking on a particular point or selecting a group of points in any plot should highlight the point(s) in all other plots. This will help see where an observation lies in different diagnostic plots and get the insights about the observation. This will help diagnose the outliers or "problematic" observations in the modeling object and hopefully give insights on why that is the case. In the case of model with tuning parameters, the plots tab display the diagnostic plots for the selected model.

### Feedback 

This package was built by Shisham Adhikari (UC Davis) under the supervision of Max Kuhn (RStudio) and Julia Silge (RStudio) as a part of the RStudio summer internship 2021. Your suggestions, feedback, complaints, or compliments are highly valued and will guide us to improve the package continuously. To give feedback, file a bug report, or ask a question, go to the [GitHub issues page](https://github.com/tidymodels/shinymodels/issues) or go to [RStudio Community](https://community.rstudio.com/) and create a post with the tag `tidymodels`. 
 
For more information on tidymodels: 

 * [`tidymodels.org`](https://www.tidymodels.org/)

 * [_Tidy Modeling with R_](https://www.tmwr.org/)
