app <- ShinyDriver$new("../../")
app$snapshotInit("test")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarid = "interactive")
app$setInputs(num_value_col = "B")
app$setInputs(factor_value_col = "Class")
app$setInputs(alpha = 0.3)
app$setInputs(size = 1.6)
app$snapshot()
app$setInputs(prob_scaling = "TRUE")
app$snapshot()
app$setInputs(sidebarid = "static")
app$snapshot()
