app <- ShinyDriver$new("../../")
app$snapshotInit("tests")

app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$setInputs(sidebarid = "interactive")
app$setInputs(num_value_col = "A")
app$setInputs(factor_value_col = "Class")
app$setInputs(alpha = 1)
app$setInputs(size = 1.1)
app$setInputs(size = 0.2)
app$setInputs(prob_scaling = "TRUE")
app$snapshot()
app$snapshot()
