app <- ShinyDriver$new("../../")
app$snapshotInit("tests")

app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$snapshot()
app$setInputs(num_value_col = "disp")
app$setInputs(alpha = 0.1)
app$setInputs(size = 1.9)
app$setInputs(size = 2)
app$snapshot()
