app <- ShinyDriver$new("../../")
app$snapshotInit("tests")

app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$setInputs(sidebarid = "static")
app$snapshot()
app$setInputs(sidebarid = "tuning")
app$setInputs(sidebarid = "static")
app$setInputs(sidebarid = "interactive")
app$setInputs(num_value_col = "Year")
app$setInputs(factor_value_col = "Location")
app$snapshot()
app$setInputs(prob_scaling = "TRUE")
app$snapshot()
